//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

public class NourritureBonbons
		{
		/* ********* *
		 	* Attributs *
		 	* ********* */
		
		#region Attributs publics
		
		public Invocations nom_prefab;
		public int _poids;
		public int Poids
		{
			get { return _poids; }
			set { _poids = value; }
		}
		
		#endregion 
		
		
		/* ******** *
			 * Méthodes *
			 * ******** */
		
		#region Méthodes 
		
		public NourritureBonbons ()
		{	
		}
		/*public Nourriture (string np)
	{	
		np = nom_prefab;
	}*/
		public NourritureBonbons (Invocations np, int _poids)
		{	
			np = nom_prefab;
			_poids = 1;
		}
		
		#region methodes publiques
		public Invocations ListeNourriture() {
			
			List<Invocations> n = new List<Invocations>();
			
			n.Add (Invocations.BONBON_ANGLAIS_BLEU);
			n.Add (Invocations.BONBON_ANGLAIS_ROSE);
			n.Add (Invocations.BONBON_ORANGE);
			n.Add (Invocations.BONBON_ROSE);
			n.Add (Invocations.BONBON_VERT);
			n.Add (Invocations.BONBON_MURE);
			
			int i = RandomNumber (0, 6);
			Invocations bonbonRandom = n[i];
			
			return bonbonRandom;
		}
		
		
		#endregion
		
		#region methodes privees
		
		private int RandomNumber(int min, int max)
		{
			Random random = new Random();
			return random.Next(min, max);
		} 
		#endregion
	}
		

#endregion